export const FETCH_MOVIES_START = 'FETCH_MOVIES_START'
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS'
export const FETCH_MOVIES_FAIL = 'FETCH_MOVIES_FAIL'

export const SET_SORT_ORDER = 'SET_SORT_ORDER'
export const SET_FILTER_VALUE = 'SET_FILTER_VALUE'

export const SET_SELECTED_MOVIE = 'SET_SELECTED_MOVIE'
